name: Pull request checks

on:
  pull_request:
    branches: ['main']

env:
  NODE_VERSION: 18.x

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - run: npm i
      - run: npm run lint
      - run: npm run test:ci
